language:
  - node_js
node_js:
  - '6'
services:
  - postgresql
addons:
  - postgresql: "9.4"
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=changeme
    - TRANSACTION_AMOUNT=changeme
    - BRAINTREE_MERCHANT_ID=changeme
    - BRAINTREE_PUBLIC_KEY=changeme
    - BRAINTREE_PRIVATE_KEY=changeme
    - MAILGUN_KEY=changeme
    - MAILGUN_DOMAIN=changeme
before_script:
  - psql -c 'create database bowtie_test;' -U postgres
  - npm install -g istanbul
script:
  - npm run test
after_script:
  - npm run coveralls
