language:
  - node_js
node_js:
  - '6'
services:
  - postgresql
addons:
  - postgresql: "9.4"
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=test
before_script:
  - psql -c 'create database bowtie_test;' -U postgres
  - npm install -g istanbul
script:
  - npm run test
after_script:
  - npm run coveralls
